# ===== STOP (движение запрещено) =====

GO_ALWAYS = {
    ""
}

STOP_ALWAYS = {
    "ZTL"
}



STOP_SIGNS = {
    "DIVIETO",
    "DIVIETO L4",
    "DIVIETO ECCETTO L4",
    "DIVIETO MEZZI PESANTI",
    "DIVIETO MEZZI NON AUTORIZZATI",
    "DIVIETO PER VEICOLI A MOTORE",
    "DIVIETO DI TRANSITO",
    "DIVIETO DI FERMATA",
    "DIVIETO DI SOSTA 00:00-24:00 RIMOZIONE FORZATA",
    "SENSO VIETATO"
}


# ===== GO (точно можно ехать) =====

GO_SIGNS = {
    "ECCETTO BUS",
    "ECCETTO BUS E TAXI",
    "ECCETTO L4",
    "ECCETTO RESIDENTI",
    "ECCETTO ELETTRICI",
    "ACCESSO CONSENTITO AI ELETTRICI",
    "FINE ZTL",
    "ZTL VARCO NON ATTIVO"
}


# ===== WARNING (предупреждения, ехать можно) =====

WARNING_SIGNS = {
    "ATTENZIONE PEDONI",
    "ATTENZIONE BAMBINI SCUOLA",
    "DOSSO ARTIFICIALE",
    "RALLENTARE",
    "LAVORI",
    "LAVORI IN CORSO",
    "LAVORI IN CORSO A 100M",
    "STRADA DISSESTATA LIMITE 10 KM/H"
}


# ===== NEUTRAL (просто информация) =====

NEUTRAL_SIGNS = {
    "ROTATORIA",
    "TUTTE LE DIREZIONI",
    "PIAZZA DEL DUOMO",
    "STAZIONE FERROVIARIA",
    "CENTRO STORICO",
    "AREA PEDONALE",
    "ZONA 30",
    "PARCHEGGIO A PAGAMENTO",
    "PASSAGGIO A LIVELLO",
    "SENSO UNICO ALTERNATO",
    "OBBLIGO DI SVOLTA A DESTRA",
    "STRADA SENZA USCITA",
    "LIMITE MASSIMO 30 KM/H"
}